Basics

In [ ]:
python_list = [1,2,3,4,5,6]
print("List \n" , python_list)

import numpy as np

numpy_array = np.array([1,2,3,4,5,6])
print("\n Numpy Array \n" , numpy_array)

# this is called 1D array


2 D array - also called matrix

In [ ]:
import numpy as np

# isme rows and col dono hote hai
numpy_array = np.array([[1,2,3],
                        [4,5,6],
                        [7,8,9]])
print(numpy_array)

Multi Dimensional Array - also called matrix

In [ ]:
import numpy as np

matrix = np.array([[2,4,6],
                   [8,10,12]])
print(matrix)

Creating arrays from python list 

In [ ]:
import numpy as np

numpy_array = np.array([1,2,3,4,5,6])
print("\n Numpy Array \n" , numpy_array)

Array with default values

In [ ]:
import numpy as np


# default 0s value
zeros_array = np.zeros(3)
print(zeros_array)

# default 1s value
one_array = np.ones(3)
print(one_array)

one1_array = np.ones([2,3])
print(one1_array)

# with specific value - use full(shape , value)
filled_arr = np.full([2,2] , 7)
print(filled_arr)

Creating sequences of array in numpy

In [ ]:
import numpy as np

arr = np.arange(1,10,2)
print(arr)

Identity Matrix

In [15]:
import numpy as np

identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
